package com.company;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.*;

public class NewJFrame extends  javax.swing.JFrame {
    StringBuilder sb;
    File f;

    private javax.swing.JButton firstJButton;
    private javax.swing.JButton secondJButton;
    private javax.swing.JButton thirdJButton;
    private javax.swing.JFileChooser jFileSelector1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {
        // initializing components
        jFileSelector1 = new javax.swing.JFileChooser();
        firstJButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        secondJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        thirdJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstJButton.setText("File selector");
        firstJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSelector(evt);
            }
        });

        jLabel1.setText("Enter Text to Search");

        secondJButton.setText("Search");
        secondJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileReader(evt);
            }
        });

        jTextArea1.setColumns(100);
        jTextArea1.setRows(50);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(100);
        jTextArea2.setRows(50);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("Original Content");

        jLabel3.setText("Searched Content");

        thirdJButton.setText("Quit");
        thirdJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jLabel2)
                                                                .addGap(91, 91, 91)
                                                                .addComponent(jLabel3))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(secondJButton)))))
                                .addContainerGap(18, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(firstJButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thirdJButton)
                                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstJButton)
                                        .addComponent(thirdJButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(secondJButton))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(7, 7, 7)
                                                .addComponent(jScrollPane1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                                .addContainerGap())))
        );
        pack();
    }// </editor-fold>
//fileSelector
    private void fileSelector(java.awt.event.ActionEvent evt) {
// TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();

// optionally set chooser options ...
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            f = chooser.getSelectedFile();

            try
            {
                BufferedReader br=new BufferedReader(new FileReader(f));
                sb=new StringBuilder();
                String line="";
                line=br.readLine();
                while(line!=null)
                {
                    sb.append(line);
                    sb.append("\n");
                    line=br.readLine();
                }

                jTextArea1.setText(sb.toString());

            }
            catch(Exception e)
            {
                System.err.println(e.toString());
            }


// read and/or display the file somehow. ....
        } else {
// user changed their mind
        }
    }
    //fileReader
    private void fileReader(java.awt.event.ActionEvent evt) {


        String sr=jTextField1.getText();
        sb.delete(0, sb.length());
        try
        {
            BufferedReader br=new BufferedReader(new FileReader(f));

            String line="";
            line=br.readLine();
            while(line!=null)
            {
                String h[]=line.split(" ");
                int len=h.length;
                for(int i=0;i<len;i++)
                {
                    if(h[i].equalsIgnoreCase(sr))
                    {
                        sb.append(line);
                        sb.append("\n");
                    }
                }

                line=br.readLine();
            }

            jTextArea2.setText(sb.toString());



        } catch(Exception e)
        {
            System.err.println(e.toString());
        }

    }
//quit
    private void quit(java.awt.event.ActionEvent evt) {
        this.dispose();
    }
}
